#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
for value in $(seq -s ' ' 1577295.3725323 2.5e5 1635024.9097855);
do
echo heat flux $value
echo crud_chem_5th.i starts
 ~/Projects/mamba-dev/mamba-dev-opt -i crud_chem_5th_2.i AuxKernels/aux_porosity/init_porosity=0.5 Materials/material_CRUD/CladHeatFluxIn=$value Outputs/file_base=crud_chem_0.5_6840_${value}_608_25 BCs/temperature_up/T_coolant=608.15 BCs/temperature_up/h_convection_coolant=6840 BCs/pressure_up/value=15616.62527
done

