// Moose Includes
#include "MambaApp.h"
#include "Moose.h"
#include "AppFactory.h"
#include "MooseSyntax.h"

// Modules
#include "ChemicalReactionsApp.h"
#include "TensorMechanicsApp.h"
#include "HeatConductionApp.h"
#include "MiscApp.h"
#include "ContactApp.h"
#include "LinearElasticityApp.h"
//#include "BisonApp.h"
//// BISON
//#include "BisonSyntax.h"
//#include "BisonRevision.h" // This file is autogenerated and contains the revision.

// First come the kernel header files
#include "CoeffTimeDerivative.h"
#include "ThermalDiffusion.h"
#include "AdvectionForHeat.h"
#include "PressureDarcy.h"
#include "AdvectionForConcentration.h"
#include "DiffusionForConcentration.h"
#include "BoricAcidSinks.h"
//#include "WaterSaturationTemperature.h"

//Dirackernels
#include "FrontSource.h"

// Next come the auxilliary kernels
#include "EnergyBalanceAux.h"
#include "CapillaryPressureAux.h"
#include "PhaseAux.h"
#include "TortuosityAux.h"
#include "PorosityAux.h"
#include "WaterSaturationPressureAux.h"
#include "WaterSaturationTemperatureAux.h"
#include "SuperheatTempAux.h"
#include "FluidVelocityAux.h"
#include "PecletAux.h"
#include "Precipitation_HBO2Aux.h"
#include "BO3_SolubilityAux.h"
#include "ConductivityFieldAux.h"
#include "ECofLiBO2.h"
#include "FluidMassFluxAux.h"
#include "HeatConductionAux.h"
#include "InterfaceVaporPressureAux.h"

// Next come the materials

#include "CRUDMaterial.h"

// Next come the boundary conditions

#include "CRUDCladNeumannBC.h"
#include "CRUDCladNeumannBCMultiApp.h"
#include "CRUDCoolantNeumannBC.h"
#include "CoupledTsatDirichletBC.h"
#include "ChimneyEvaporationNeumannBC.h"
#include "ChimneyEnthalpyFlow.h"
#include "CRUDChimneyConcentrationMixedBC.h"
#include "ConditionLeftTemp.h"
#include "ChimneyPressureDirichletBC.h"
#include "OnOffChimneyEvaporationNeumannBC.h"
#include "OnOffCoupledTsatDirichletBC.h"
#include "ChimneyVaporVelocity.h"

//Functions
#include "PostprocessorFunction.h"
#include "PPCombinationFunc.h"
#include "EvaporationFunction.h"

//#include "VarCombine.h"

//userobjects
#include "TrackDiracFront.h"

// Finally, the postprocessors
#include "VaporHeight.h"
#include "LiquidHeight.h"
#include "VelocityExit.h"
#include "AreaAverageBoron.h"
#include "IntegratedSideFlux.h"
#include "NodalMinValue.h"
#include "WaterSideFluxAverage.h"
#include "LiquidInterfaceVelocity.h"

//transfers
#include "MultiAppSamplePostprocessorTransferBase.h"
#include "MultiAppSamplePostprocessorTransferFlux.h"

template<>
InputParameters validParams<MambaApp>()
{
  InputParameters params = validParams<MooseApp>();
  return params;
}

MambaApp::MambaApp(const InputParameters & parameters) :
    MooseApp(parameters)
{
  srand(processor_id());

  // Register all the user-created objects for incorporation and use
  Moose::registerObjects(_factory);
  ChemicalReactionsApp::registerObjects(_factory);
  ContactApp::registerObjects(_factory); // for bison
  LinearElasticityApp::registerObjects(_factory); // for bison
//  SolidMechanicsApp::registerObjects(_factory);
  TensorMechanicsApp::registerObjects(_factory);
  HeatConductionApp::registerObjects(_factory);
  MiscApp::registerObjects(_factory);
//  BisonApp::registerObjects(_factory);
  MambaApp::registerObjects(_factory);

  // Associate Parser Syntax
  Moose::associateSyntax(_syntax, _action_factory);
  ChemicalReactionsApp::associateSyntax(_syntax, _action_factory);
//  SolidMechanicsApp::associateSyntax(_syntax, _action_factory);
  ContactApp::associateSyntax(_syntax, _action_factory); // for bison
  TensorMechanicsApp::associateSyntax(_syntax, _action_factory);
  HeatConductionApp::associateSyntax(_syntax, _action_factory);
  MiscApp::associateSyntax(_syntax, _action_factory);
//  Bison::associateSyntax(_syntax, _action_factory);
  MambaApp::associateSyntax(_syntax, _action_factory);
}

MambaApp::~MambaApp()
{
}

void
MambaApp::registerApps()
{
  registerApp(MambaApp);
//  registerApp(BisonApp);
}

void
MambaApp::registerObjects(Factory & factory)
{
  // First come the kernels

  // Our new advection-diffusion kernel that accepts an auxKernel's aqueous species diffusivity,
  // the permeability material property, and the coupled pressure variable (of which the grad is taken)
  registerKernel(CoeffTimeDerivative);
  registerKernel(AdvectionForConcentration);
  registerKernel(DiffusionForConcentration);
  registerKernel(BoricAcidSinks);
//  registerAux(WaterSaturationTemperature);

  // Our new Darcy flow kernel that accepts the permeability material property

  registerKernel(PressureDarcy);

  // Our new thermal diffusion kernel that accepts the k_cond (thermal conductivity) material property

  registerKernel(ThermalDiffusion);
  registerKernel(AdvectionForHeat);

// Dirachkernels
  registerDiracKernel(FrontSource);

  // Next come the auxilliary kernels
  registerAux(EnergyBalanceAux);
  registerAux(CapillaryPressureAux);
  registerAux(PhaseAux);
  registerAux(TortuosityAux);
  registerAux(PorosityAux);
  registerAux(WaterSaturationPressureAux);
  registerAux(WaterSaturationTemperatureAux);
  registerAux(SuperheatTempAux);
  registerAux(FluidVelocityAux);
  registerAux(PecletAux);
  registerAux(Precipitation_HBO2Aux);
  registerAux(BO3_SolubilityAux);
  registerAux(ConductivityFieldAux);
  registerAux(ECofLiBO2);
  registerAux(FluidMassFluxAux);
  registerAux(HeatConductionAux);
  registerAux(InterfaceVaporPressureAux);

  // Next come the materials

  // Register our new CRUD material class so we can use it.

  registerMaterial(CRUDMaterial);

  // Next come the boundary conditions

  registerBoundaryCondition(CRUDCladNeumannBC);
  registerBoundaryCondition(CRUDCladNeumannBCMultiApp);
  registerBoundaryCondition(CRUDCoolantNeumannBC);
  registerBoundaryCondition(CoupledTsatDirichletBC);
  registerBoundaryCondition(ChimneyEvaporationNeumannBC);
  registerBoundaryCondition(ChimneyEnthalpyFlow);
  registerBoundaryCondition(CRUDChimneyConcentrationMixedBC);
  registerBoundaryCondition(ConditionLeftTemp);
  registerBoundaryCondition(ChimneyPressureDirichletBC);
  registerBoundaryCondition(OnOffChimneyEvaporationNeumannBC);
  registerBoundaryCondition(OnOffCoupledTsatDirichletBC);
  registerBoundaryCondition(ChimneyVaporVelocity);

  //userobjects
  registerUserObject(TrackDiracFront);


  //Functions;
  registerFunction(PostprocessorFunction);
  registerFunction(PPCombinationFunc);
  registerFunction(EvaporationFunction);
 // registerPostprocessor(VarCombine);

  // Finally come the postprocessors
  registerPostprocessor(VaporHeight);
  registerPostprocessor(LiquidHeight);
  registerPostprocessor(VelocityExit);
  registerPostprocessor(AreaAverageBoron);
  registerPostprocessor(IntegratedSideFlux);
  registerPostprocessor(NodalMinValue);
  registerPostprocessor(WaterSideFluxAverage);
  registerPostprocessor(LiquidInterfaceVelocity);

  //register transfer
  registerTransfer(MultiAppSamplePostprocessorTransferBase);
  registerTransfer(MultiAppSamplePostprocessorTransferFlux);
}

void
MambaApp::associateSyntax(Syntax & syntax, ActionFactory & action_factory)
{
}
